#!/bin/sh

set -e

mypy --strict .

find -name '*.py' | xargs autopep8 -d > /tmp/autopep8diff

[ "$(cat /tmp/autopep8diff)" != "" ] && cat /tmp/autopep8diff && exit 1


if test "$1" = "quick"; then
    pytest -k 'not dsa and not reducible and not nip'
else
    time -p pytest
fi

exit 0
